(define (problem HRI_prob)
(:domain HRI_dom)


(:objects 
          
    Apple Sliced_Apple Mango Sliced_Mango Avocado Sliced_Avocado Fruit_Salad Banana Sliced_Banana - fruit
        
    Pasta Cooked_Pasta cereal Cooked_cereal - food

    eggs omelete scrambled_eggs - ToFry

    Raw_eggs boiled_eggs rice cooked_rice lentil cooked_lentil soup prepared_soup - ToBoil

    chicken roasted_chicken bread roasted_sandwich - ToRoast

    Potato Veggie Mashed_Potato - vegetable
        
    wine milk water yogurt juice sweet_juice coke ice_tea - drink
        
    CellPhone cup Casual_clothes Office_clothes Gym_Clothes - obj

    Laptop - sensitive_obj
        
    mold cake - tobake

)


(:init
    
    ;; init_1
    ; (agent_at kitchen) 
    ; (Human_at livingroom)
    ; (agent_near stove_burner_1 kitchen)
    ; (human_near working_table livingroom)

    ;; init_2
    ; (agent_at storeroom)  
    ; (Human_at livingroom)
    ; (agent_near laundrybag storeroom)
    ; (human_near working_table livingroom)
    
    ;; init_3
    (agent_at kitchen) 
    (Human_at kitchen)
    (agent_near sink kitchen)
    (human_near dining_table kitchen)

    ;; init_4
    ; (agent_at livingroom)
    ; (Human_at livingroom)
    ; (agent_near closet livingroom)
    ; (human_near working_table livingroom)

    (agent_switched_off faucet sink Kitchen)  
    (agent_switched_off Burner stove_burner_1 Kitchen) 
    (agent_switched_off Burner stove_burner_2 Kitchen) 
    (agent_switched_off Burner stove_burner_3 Kitchen) 
    (agent_switched_off Burner stove_burner_4 Kitchen) 
    (agent_switched_off oven_switch oven Kitchen) 
    (agent_switched_off washingmachine_Switch washingmachine Bathroom)
    (agent_switched_off Laptop_Switch working_table livingroom)
    
    (human_switched_off faucet sink Kitchen)  
    (human_switched_off Burner stove_burner_1 Kitchen) 
    (human_switched_off Burner stove_burner_2 Kitchen) 
    (human_switched_off Burner stove_burner_3 Kitchen) 
    (human_switched_off Burner stove_burner_4 Kitchen) 
    (human_switched_off oven_switch oven Kitchen) 
    (human_switched_off washingmachine_Switch washingmachine Bathroom)
    (human_switched_off Laptop_Switch working_table livingroom)


    
    (agent_switch_off extinguisher)
    (human_switch_off extinguisher)
    (human_switch_off Vacuum_Cleaner)
    (agent_switch_off Vacuum_Cleaner)
    (human_switch_off Color_lights)
    (agent_switch_off Color_lights)
    (human_switch_off TV)
    (agent_switch_off TV)
    (agent_switch_off musicplayer)
    (human_switch_off musicplayer)
    (agent_switch_off Laptop)
    (human_switch_off Laptop)

    
    (B_obj_at Faucet Kitchen)
    (B_obj_at burner Kitchen)
    (B_obj_at oven_switch Kitchen)
    (B_obj_at Dishwasher_Switch Kitchen)
    (B_obj_at extinguisher StoreRoom)
    (B_obj_at vacuum_cleaner StoreRoom)
    (B_obj_at DustMop Bathroom)
    (B_obj_at DustingCloth StoreRoom)
    (B_obj_at TV livingroom)
    (B_obj_at computer livingRoom)
    (B_obj_at musicplayer livingroom)
    (stuff_at Laptop working_table livingroom)
    (stuff_at CellPhone dining_table kitchen)
    (B_obj_at color_lights livingroom)


    (stuff_at Dirtydishes dining_Table Kitchen)

    (receptacle_at plate rack Kitchen)
    (receptacle_at glass cabinet Kitchen)
    (receptacle_at pan_1 shelf kitchen)
    (receptacle_at pan_2 shelf kitchen)
    (receptacle_at bowl cabinet kitchen)
    (receptacle_at metal_pot rack kitchen) ;changed from shelf to rack
    (receptacle_at tray rack kitchen)
    (receptacle_at office_bag ironing_board livingroom)

    (not(open oven Kitchen))
    (not(open shelf Kitchen))

    ;Fruits and Vegetables
    (stuff_at Apple fridge Kitchen)
    (equal Apple Sliced_Apple)
  
    (stuff_at Mango fridge Kitchen)
    (equal Mango Sliced_Mango)

    (stuff_at banana fridge Kitchen)
    (equal banana Sliced_banana)

    (stuff_at Avocado fridge Kitchen)
    (equal Avocado Sliced_Avocado)
    
    (stuff_at Veggie fridge Kitchen) 
    (equal Veggie Veggie)

    (stuff_at Potato fridge Kitchen) 
    (equal Potato Potato)

    (salad Fruit_Salad)

    ;Food items
    (stuff_at Pasta cabinet Kitchen)
    (equal Pasta Cooked_Pasta)
    (cleaned Pasta)

    (stuff_at cereal shelf Kitchen)
    (equal cereal Cooked_cereal)
    (cleaned cereal)

    (stuff_at Raw_eggs fridge Kitchen) ;ToBoil
    (equal Raw_eggs Boiled_eggs)
    (cleaned Raw_eggs)

    (stuff_at eggs fridge Kitchen) ;ToFry
    (equal eggs omelete)
    (equal eggs scrambled_eggs)
    (cleaned eggs)

    (stuff_at rice cabinet Kitchen)  ;ToBoil
    (equal rice Cooked_rice)
    (cleaned rice)

    (stuff_at lentil cabinet Kitchen) ;ToBoil
    (equal lentil Cooked_lentil)
    (cleaned lentil)

    (stuff_at soup cabinet Kitchen) ;ToBoil
    (equal soup prepared_soup)
    (cleaned soup)

    (stuff_at chicken fridge Kitchen) ;ToRoast
    (equal chicken roasted_chicken)
    (cleaned chicken)

    (stuff_at bread cabinet Kitchen)  ;ToRoast
    (equal bread roasted_sandwich)
    (Cleaned bread)
    
    (stuff_at Medicines cabinet kitchen)
        
    (food_remaining)

    ;Baking items
    (stuff_at mold shelf Kitchen)
    (equal mold cake)
 
     
    ;Drinking items
    (stuff_at wine shelf Kitchen)
    (stuff_at milk fridge Kitchen)
    (stuff_at water fridge Kitchen)
    (stuff_at yogurt fridge Kitchen)
    (stuff_at juice fridge Kitchen)
    (stuff_at sweet_juice fridge Kitchen)
    (stuff_at coke fridge Kitchen)
    (stuff_at ice_tea fridge Kitchen)

    ;Pizza items
    (stuff_at pizza_base cabinet kitchen)
    (stuff_at Veggy fridge Kitchen)
    (stuff_at Sauce fridge Kitchen)
    (not(pizza_baked))
    (not(pizza_base_prepared))

    ;Washing
    (stuff_at Clothes laundrybag storeroom)
    (stuff_at casual_clothes closet livingroom)
    (stuff_at office_clothes closet livingroom)
    (stuff_at gym_clothes closet livingroom)

    (r_at cabinet Kitchen)
    (r_at rack Kitchen)
    (r_at shelf Kitchen)
    (r_at stove_burner_1 Kitchen)
    (r_at stove_burner_2 Kitchen)
    (r_at stove_burner_3 Kitchen)
    (r_at stove_burner_4 Kitchen)
    (r_at countertop Kitchen)
    (r_at sink Kitchen)
    (r_at oven Kitchen)
    (r_at fridge Kitchen)
    (r_at ironing_board LivingRoom)
    (r_at dining_table Kitchen)
    (r_at washingmachine Bathroom)
    (r_at laundrybag Storeroom)
    (r_at closet LivingRoom)
    (r_at dustbin_1 Kitchen)
    (r_at working_table LivingRoom)
    ; (r_at bed livingRoom)


    (stuff_at water_bottle fridge kitchen)


    (not_burner sink)
    (not_burner countertop)
    (not_burner oven)
    (not_burner dustbin_1)
    (not_burner fridge)
    (not_burner shelf)
    (not_burner rack)
    (not_burner cabinet)
    (not_burner washingmachine)
    (not_burner laundrybag)
    (not_burner ironing_board)
    (not_burner closet)
    (not_burner dining_table)
    (not_burner working_table)

    
;; Duration between immobile receptacles

 (=(human_dur cabinet cabinet)0)
(=(human_dur cabinet rack)5)
(=(human_dur cabinet shelf)27)
(=(human_dur cabinet stove_burner_1)22)
(=(human_dur cabinet stove_burner_2)23)
(=(human_dur cabinet stove_burner_3)21)
(=(human_dur cabinet stove_burner_4)21)
(=(human_dur cabinet countertop)15)
(=(human_dur cabinet sink)28)
(=(human_dur cabinet oven)27)
(=(human_dur cabinet fridge)16)
(=(human_dur cabinet dining_table)18)
(=(human_dur cabinet dustbin_1)36)
(=(human_dur rack cabinet)5)
(=(human_dur rack rack)0)
(=(human_dur rack shelf)31)
(=(human_dur rack stove_burner_1)19)
(=(human_dur rack stove_burner_2)19)
(=(human_dur rack stove_burner_3)17)
(=(human_dur rack stove_burner_4)18)
(=(human_dur rack countertop)10)
(=(human_dur rack sink)26)
(=(human_dur rack oven)30)
(=(human_dur rack fridge)21)
(=(human_dur rack dining_table)19)
(=(human_dur rack dustbin_1)38)
(=(human_dur shelf cabinet)27)
(=(human_dur shelf rack)31)
(=(human_dur shelf shelf)0)
(=(human_dur shelf stove_burner_1)30)
(=(human_dur shelf stove_burner_2)33)
(=(human_dur shelf stove_burner_3)30)
(=(human_dur shelf stove_burner_4)32)
(=(human_dur shelf countertop)32)
(=(human_dur shelf sink)31)
(=(human_dur shelf oven)2)
(=(human_dur shelf fridge)17)
(=(human_dur shelf dining_table)14)
(=(human_dur shelf dustbin_1)13)
(=(human_dur stove_burner_1 cabinet)22)
(=(human_dur stove_burner_1 rack)19)
(=(human_dur stove_burner_1 shelf)30)
(=(human_dur stove_burner_1 stove_burner_1)0)
(=(human_dur stove_burner_1 stove_burner_2)1)
(=(human_dur stove_burner_1 stove_burner_3)1)
(=(human_dur stove_burner_1 stove_burner_4)2)
(=(human_dur stove_burner_1 countertop)9)
(=(human_dur stove_burner_1 sink)6)
(=(human_dur stove_burner_1 oven)29)
(=(human_dur stove_burner_1 fridge)32)
(=(human_dur stove_burner_1 dining_table)16)
(=(human_dur stove_burner_1 dustbin_1)30)
(=(human_dur stove_burner_2 cabinet)23)
(=(human_dur stove_burner_2 rack)19)
(=(human_dur stove_burner_2 shelf)33)
(=(human_dur stove_burner_2 stove_burner_1)1)
(=(human_dur stove_burner_2 stove_burner_2)0)
(=(human_dur stove_burner_2 stove_burner_3)2)
(=(human_dur stove_burner_2 stove_burner_4)1)
(=(human_dur stove_burner_2 countertop)9)
(=(human_dur stove_burner_2 sink)7)
(=(human_dur stove_burner_2 oven)30)
(=(human_dur stove_burner_2 fridge)33)
(=(human_dur stove_burner_2 dining_table)18)
(=(human_dur stove_burner_2 dustbin_1)32)
(=(human_dur stove_burner_3 cabinet)21)
(=(human_dur stove_burner_3 rack)17)
(=(human_dur stove_burner_3 shelf)30)
(=(human_dur stove_burner_3 stove_burner_1)1)
(=(human_dur stove_burner_3 stove_burner_2)2)
(=(human_dur stove_burner_3 stove_burner_3)0)
(=(human_dur stove_burner_3 stove_burner_4)1)
(=(human_dur stove_burner_3 countertop)7)
(=(human_dur stove_burner_3 sink)8)
(=(human_dur stove_burner_3 oven)29)
(=(human_dur stove_burner_3 fridge)30)
(=(human_dur stove_burner_3 dining_table)15)
(=(human_dur stove_burner_3 dustbin_1)31)
(=(human_dur stove_burner_4 cabinet)21)
(=(human_dur stove_burner_4 rack)18)
(=(human_dur stove_burner_4 shelf)32)
(=(human_dur stove_burner_4 stove_burner_1)2)
(=(human_dur stove_burner_4 stove_burner_2)1)
(=(human_dur stove_burner_4 stove_burner_3)1)
(=(human_dur stove_burner_4 stove_burner_4)0)
(=(human_dur stove_burner_4 countertop)7)
(=(human_dur stove_burner_4 sink)9)
(=(human_dur stove_burner_4 oven)30)
(=(human_dur stove_burner_4 fridge)32)
(=(human_dur stove_burner_4 dining_table)18)
(=(human_dur stove_burner_4 dustbin_1)33)
(=(human_dur countertop cabinet)15)
(=(human_dur countertop rack)10)
(=(human_dur countertop shelf)32)
(=(human_dur countertop stove_burner_1)9)
(=(human_dur countertop stove_burner_2)9)
(=(human_dur countertop stove_burner_3)7)
(=(human_dur countertop stove_burner_4)7)
(=(human_dur countertop countertop)0)
(=(human_dur countertop sink)15)
(=(human_dur countertop oven)30)
(=(human_dur countertop fridge)28)
(=(human_dur countertop dining_table)18)
(=(human_dur countertop dustbin_1)35)
(=(human_dur sink cabinet)28)
(=(human_dur sink rack)26)
(=(human_dur sink shelf)31)
(=(human_dur sink stove_burner_1)6)
(=(human_dur sink stove_burner_2)7)
(=(human_dur sink stove_burner_3)8)
(=(human_dur sink stove_burner_4)9)
(=(human_dur sink countertop)15)
(=(human_dur sink sink)0)
(=(human_dur sink oven)28)
(=(human_dur sink fridge)35)
(=(human_dur sink dining_table)17)
(=(human_dur sink dustbin_1)27)
(=(human_dur oven cabinet)27)
(=(human_dur oven rack)30)
(=(human_dur oven shelf)2)
(=(human_dur oven stove_burner_1)29)
(=(human_dur oven stove_burner_2)30)
(=(human_dur oven stove_burner_3)29)
(=(human_dur oven stove_burner_4)30)
(=(human_dur oven countertop)30)
(=(human_dur oven sink)28)
(=(human_dur oven oven)0)
(=(human_dur oven fridge)18)
(=(human_dur oven dining_table)12)
(=(human_dur oven dustbin_1)10)
(=(human_dur fridge cabinet)16)
(=(human_dur fridge rack)21)
(=(human_dur fridge shelf)17)
(=(human_dur fridge stove_burner_1)32)
(=(human_dur fridge stove_burner_2)33)
(=(human_dur fridge stove_burner_3)30)
(=(human_dur fridge stove_burner_4)32)
(=(human_dur fridge countertop)28)
(=(human_dur fridge sink)35)
(=(human_dur fridge oven)18)
(=(human_dur fridge fridge)0)
(=(human_dur fridge dining_table)18)
(=(human_dur fridge dustbin_1)30)
(=(human_dur dining_table cabinet)18)
(=(human_dur dining_table rack)19)
(=(human_dur dining_table shelf)14)
(=(human_dur dining_table stove_burner_1)16)
(=(human_dur dining_table stove_burner_2)18)
(=(human_dur dining_table stove_burner_3)15)
(=(human_dur dining_table stove_burner_4)18)
(=(human_dur dining_table countertop)18)
(=(human_dur dining_table sink)17)
(=(human_dur dining_table oven)12)
(=(human_dur dining_table fridge)18)
(=(human_dur dining_table dining_table)0)
(=(human_dur dining_table dustbin_1)18)
(=(human_dur dustbin_1 cabinet)36)
(=(human_dur dustbin_1 rack)38)
(=(human_dur dustbin_1 shelf)13)
(=(human_dur dustbin_1 stove_burner_1)30)
(=(human_dur dustbin_1 stove_burner_2)32)
(=(human_dur dustbin_1 stove_burner_3)31)
(=(human_dur dustbin_1 stove_burner_4)33)
(=(human_dur dustbin_1 countertop)35)
(=(human_dur dustbin_1 sink)27)
(=(human_dur dustbin_1 oven)10)
(=(human_dur dustbin_1 fridge)30)
(=(human_dur dustbin_1 dining_table)18)
(=(human_dur dustbin_1 dustbin_1)0)
(=(human_dur cabinet laundrybag)51)
(=(human_dur rack laundrybag)52)
(=(human_dur shelf laundrybag)34)
(=(human_dur stove_burner_1 laundrybag)40)
(=(human_dur stove_burner_2 laundrybag)42)
(=(human_dur stove_burner_3 laundrybag)41)
(=(human_dur stove_burner_4 laundrybag)43)
(=(human_dur countertop laundrybag)46)
(=(human_dur sink laundrybag)36)
(=(human_dur oven laundrybag)31)
(=(human_dur fridge laundrybag)48)
(=(human_dur dining_table laundrybag)32)
(=(human_dur dustbin_1 laundrybag)24)
(=(human_dur cabinet ironing_board)70)
(=(human_dur cabinet closet)74)
(=(human_dur cabinet working_table)61)
(=(human_dur rack ironing_board)73)
(=(human_dur rack closet)76)
(=(human_dur rack working_table)64)
(=(human_dur shelf ironing_board)44)
(=(human_dur shelf closet)48)
(=(human_dur shelf working_table)35)
(=(human_dur stove_burner_1 ironing_board)67)
(=(human_dur stove_burner_1 closet)70)
(=(human_dur stove_burner_1 working_table)58)
(=(human_dur stove_burner_2 ironing_board)69)
(=(human_dur stove_burner_2 closet)72)
(=(human_dur stove_burner_2 working_table)59)
(=(human_dur stove_burner_3 ironing_board)67)
(=(human_dur stove_burner_3 closet)71)
(=(human_dur stove_burner_3 working_table)58)
(=(human_dur stove_burner_4 ironing_board)69)
(=(human_dur stove_burner_4 closet)73)
(=(human_dur stove_burner_4 working_table)60)
(=(human_dur countertop ironing_board)71)
(=(human_dur countertop closet)75)
(=(human_dur countertop working_table)62)
(=(human_dur sink ironing_board)65)
(=(human_dur sink closet)69)
(=(human_dur sink working_table)56)
(=(human_dur oven ironing_board)43)
(=(human_dur oven closet)46)
(=(human_dur oven working_table)33)
(=(human_dur fridge ironing_board)62)
(=(human_dur fridge closet)66)
(=(human_dur fridge working_table)53)
(=(human_dur dining_table ironing_board)53)
(=(human_dur dining_table closet)56)
(=(human_dur dining_table working_table)44)
(=(human_dur dustbin_1 ironing_board)39)
(=(human_dur dustbin_1 closet)43)
(=(human_dur dustbin_1 working_table)30)
(=(human_dur cabinet washingmachine)66)
(=(human_dur rack washingmachine)69)
(=(human_dur shelf washingmachine)40)
(=(human_dur stove_burner_1 washingmachine)63)
(=(human_dur stove_burner_2 washingmachine)65)
(=(human_dur stove_burner_3 washingmachine)63)
(=(human_dur stove_burner_4 washingmachine)65)
(=(human_dur countertop washingmachine)67)
(=(human_dur sink washingmachine)61)
(=(human_dur oven washingmachine)38)
(=(human_dur fridge washingmachine)58)
(=(human_dur dining_table washingmachine)49)
(=(human_dur dustbin_1 washingmachine)35)
(=(human_dur laundrybag cabinet)51)
(=(human_dur laundrybag rack)52)
(=(human_dur laundrybag shelf)34)
(=(human_dur laundrybag stove_burner_1)40)
(=(human_dur laundrybag stove_burner_2)42)
(=(human_dur laundrybag stove_burner_3)41)
(=(human_dur laundrybag stove_burner_4)43)
(=(human_dur laundrybag countertop)46)
(=(human_dur laundrybag sink)36)
(=(human_dur laundrybag oven)31)
(=(human_dur laundrybag fridge)48)
(=(human_dur laundrybag dining_table)32)
(=(human_dur laundrybag dustbin_1)24)
(=(human_dur laundrybag laundrybag)0)
(=(human_dur laundrybag ironing_board)63)
(=(human_dur laundrybag closet)67)
(=(human_dur laundrybag working_table)54)
(=(human_dur laundrybag washingmachine)59)
(=(human_dur ironing_board cabinet)70)
(=(human_dur ironing_board rack)73)
(=(human_dur ironing_board shelf)44)
(=(human_dur ironing_board stove_burner_1)67)
(=(human_dur ironing_board stove_burner_2)69)
(=(human_dur ironing_board stove_burner_3)67)
(=(human_dur ironing_board stove_burner_4)69)
(=(human_dur ironing_board countertop)71)
(=(human_dur ironing_board sink)65)
(=(human_dur ironing_board oven)43)
(=(human_dur ironing_board fridge)62)
(=(human_dur ironing_board dining_table)53)
(=(human_dur ironing_board dustbin_1)39)
(=(human_dur closet cabinet)74)
(=(human_dur closet rack)76)
(=(human_dur closet shelf)48)
(=(human_dur closet stove_burner_1)70)
(=(human_dur closet stove_burner_2)72)
(=(human_dur closet stove_burner_3)71)
(=(human_dur closet stove_burner_4)73)
(=(human_dur closet countertop)75)
(=(human_dur closet sink)69)
(=(human_dur closet oven)46)
(=(human_dur closet fridge)66)
(=(human_dur closet dining_table)56)
(=(human_dur closet dustbin_1)43)
(=(human_dur working_table cabinet)61)
(=(human_dur working_table rack)64)
(=(human_dur working_table shelf)35)
(=(human_dur working_table stove_burner_1)58)
(=(human_dur working_table stove_burner_2)59)
(=(human_dur working_table stove_burner_3)58)
(=(human_dur working_table stove_burner_4)60)
(=(human_dur working_table countertop)62)
(=(human_dur working_table sink)56)
(=(human_dur working_table oven)33)
(=(human_dur working_table fridge)53)
(=(human_dur working_table dining_table)44)
(=(human_dur working_table dustbin_1)30)
(=(human_dur ironing_board laundrybag)63)
(=(human_dur closet laundrybag)67)
(=(human_dur working_table laundrybag)54)
(=(human_dur ironing_board ironing_board)0)
(=(human_dur ironing_board closet)8)
(=(human_dur ironing_board working_table)31)
(=(human_dur closet ironing_board)8)
(=(human_dur closet closet)0)
(=(human_dur closet working_table)29)
(=(human_dur working_table ironing_board)31)
(=(human_dur working_table closet)29)
(=(human_dur working_table working_table)0)
(=(human_dur ironing_board washingmachine)31)
(=(human_dur closet washingmachine)38)
(=(human_dur working_table washingmachine)44)
(=(human_dur washingmachine cabinet)66)
(=(human_dur washingmachine rack)69)
(=(human_dur washingmachine shelf)40)
(=(human_dur washingmachine stove_burner_1)63)
(=(human_dur washingmachine stove_burner_2)65)
(=(human_dur washingmachine stove_burner_3)63)
(=(human_dur washingmachine stove_burner_4)65)
(=(human_dur washingmachine countertop)67)
(=(human_dur washingmachine sink)61)
(=(human_dur washingmachine oven)38)
(=(human_dur washingmachine fridge)58)
(=(human_dur washingmachine dining_table)49)
(=(human_dur washingmachine dustbin_1)35)
(=(human_dur washingmachine laundrybag)59)
(=(human_dur washingmachine ironing_board)31)
(=(human_dur washingmachine closet)38)
(=(human_dur washingmachine working_table)44)
(=(human_dur washingmachine washingmachine)0)
   




(=(agent_dur cabinet cabinet)0)
(=(agent_dur cabinet rack)7)
(=(agent_dur cabinet shelf)36)
(=(agent_dur cabinet stove_burner_1)29)
(=(agent_dur cabinet stove_burner_2)30)
(=(agent_dur cabinet stove_burner_3)27)
(=(agent_dur cabinet stove_burner_4)28)
(=(agent_dur cabinet countertop)19)
(=(agent_dur cabinet sink)37)
(=(agent_dur cabinet oven)36)
(=(agent_dur cabinet fridge)21)
(=(agent_dur cabinet dining_table)24)
(=(agent_dur cabinet dustbin_1)48)
(=(agent_dur rack cabinet)7)
(=(agent_dur rack rack)0)
(=(agent_dur rack shelf)40)
(=(agent_dur rack stove_burner_1)25)
(=(agent_dur rack stove_burner_2)25)
(=(agent_dur rack stove_burner_3)22)
(=(agent_dur rack stove_burner_4)23)
(=(agent_dur rack countertop)14)
(=(agent_dur rack sink)33)
(=(agent_dur rack oven)40)
(=(agent_dur rack fridge)28)
(=(agent_dur rack dining_table)25)
(=(agent_dur rack dustbin_1)50)
(=(agent_dur shelf cabinet)36)
(=(agent_dur shelf rack)40)
(=(agent_dur shelf shelf)0)
(=(agent_dur shelf stove_burner_1)40)
(=(agent_dur shelf stove_burner_2)43)
(=(agent_dur shelf stove_burner_3)40)
(=(agent_dur shelf stove_burner_4)42)
(=(agent_dur shelf countertop)42)
(=(agent_dur shelf sink)40)
(=(agent_dur shelf oven)3)
(=(agent_dur shelf fridge)22)
(=(agent_dur shelf dining_table)18)
(=(agent_dur shelf dustbin_1)17)
(=(agent_dur stove_burner_1 cabinet)29)
(=(agent_dur stove_burner_1 rack)25)
(=(agent_dur stove_burner_1 shelf)40)
(=(agent_dur stove_burner_1 stove_burner_1)0)
(=(agent_dur stove_burner_1 stove_burner_2)2)
(=(agent_dur stove_burner_1 stove_burner_3)1)
(=(agent_dur stove_burner_1 stove_burner_4)3)
(=(agent_dur stove_burner_1 countertop)11)
(=(agent_dur stove_burner_1 sink)8)
(=(agent_dur stove_burner_1 oven)37)
(=(agent_dur stove_burner_1 fridge)41)
(=(agent_dur stove_burner_1 dining_table)21)
(=(agent_dur stove_burner_1 dustbin_1)40)
(=(agent_dur stove_burner_2 cabinet)30)
(=(agent_dur stove_burner_2 rack)25)
(=(agent_dur stove_burner_2 shelf)43)
(=(agent_dur stove_burner_2 stove_burner_1)2)
(=(agent_dur stove_burner_2 stove_burner_2)0)
(=(agent_dur stove_burner_2 stove_burner_3)3)
(=(agent_dur stove_burner_2 stove_burner_4)1)
(=(agent_dur stove_burner_2 countertop)11)
(=(agent_dur stove_burner_2 sink)9)
(=(agent_dur stove_burner_2 oven)40)
(=(agent_dur stove_burner_2 fridge)44)
(=(agent_dur stove_burner_2 dining_table)23)
(=(agent_dur stove_burner_2 dustbin_1)42)
(=(agent_dur stove_burner_3 cabinet)27)
(=(agent_dur stove_burner_3 rack)22)
(=(agent_dur stove_burner_3 shelf)40)
(=(agent_dur stove_burner_3 stove_burner_1)1)
(=(agent_dur stove_burner_3 stove_burner_2)3)
(=(agent_dur stove_burner_3 stove_burner_3)0)
(=(agent_dur stove_burner_3 stove_burner_4)2)
(=(agent_dur stove_burner_3 countertop)9)
(=(agent_dur stove_burner_3 sink)11)
(=(agent_dur stove_burner_3 oven)37)
(=(agent_dur stove_burner_3 fridge)40)
(=(agent_dur stove_burner_3 dining_table)20)
(=(agent_dur stove_burner_3 dustbin_1)40)
(=(agent_dur stove_burner_4 cabinet)28)
(=(agent_dur stove_burner_4 rack)23)
(=(agent_dur stove_burner_4 shelf)42)
(=(agent_dur stove_burner_4 stove_burner_1)3)
(=(agent_dur stove_burner_4 stove_burner_2)1)
(=(agent_dur stove_burner_4 stove_burner_3)2)
(=(agent_dur stove_burner_4 stove_burner_4)0)
(=(agent_dur stove_burner_4 countertop)9)
(=(agent_dur stove_burner_4 sink)11)
(=(agent_dur stove_burner_4 oven)40)
(=(agent_dur stove_burner_4 fridge)42)
(=(agent_dur stove_burner_4 dining_table)23)
(=(agent_dur stove_burner_4 dustbin_1)43)
(=(agent_dur countertop cabinet)19)
(=(agent_dur countertop rack)14)
(=(agent_dur countertop shelf)42)
(=(agent_dur countertop stove_burner_1)11)
(=(agent_dur countertop stove_burner_2)11)
(=(agent_dur countertop stove_burner_3)9)
(=(agent_dur countertop stove_burner_4)9)
(=(agent_dur countertop countertop)0)
(=(agent_dur countertop sink)20)
(=(agent_dur countertop oven)40)
(=(agent_dur countertop fridge)37)
(=(agent_dur countertop dining_table)23)
(=(agent_dur countertop dustbin_1)46)
(=(agent_dur sink cabinet)37)
(=(agent_dur sink rack)33)
(=(agent_dur sink shelf)40)
(=(agent_dur sink stove_burner_1)8)
(=(agent_dur sink stove_burner_2)9)
(=(agent_dur sink stove_burner_3)11)
(=(agent_dur sink stove_burner_4)11)
(=(agent_dur sink countertop)20)
(=(agent_dur sink sink)0)
(=(agent_dur sink oven)37)
(=(agent_dur sink fridge)46)
(=(agent_dur sink dining_table)22)
(=(agent_dur sink dustbin_1)36)
(=(agent_dur oven cabinet)36)
(=(agent_dur oven rack)40)
(=(agent_dur oven shelf)3)
(=(agent_dur oven stove_burner_1)37)
(=(agent_dur oven stove_burner_2)40)
(=(agent_dur oven stove_burner_3)37)
(=(agent_dur oven stove_burner_4)40)
(=(agent_dur oven countertop)40)
(=(agent_dur oven sink)37)
(=(agent_dur oven oven)0)
(=(agent_dur oven fridge)24)
(=(agent_dur oven dining_table)16)
(=(agent_dur oven dustbin_1)14)
(=(agent_dur fridge cabinet)21)
(=(agent_dur fridge rack)28)
(=(agent_dur fridge shelf)22)
(=(agent_dur fridge stove_burner_1)41)
(=(agent_dur fridge stove_burner_2)44)
(=(agent_dur fridge stove_burner_3)40)
(=(agent_dur fridge stove_burner_4)42)
(=(agent_dur fridge countertop)37)
(=(agent_dur fridge sink)46)
(=(agent_dur fridge oven)24)
(=(agent_dur fridge fridge)0)
(=(agent_dur fridge dining_table)24)
(=(agent_dur fridge dustbin_1)39)
(=(agent_dur dining_table cabinet)24)
(=(agent_dur dining_table rack)25)
(=(agent_dur dining_table shelf)18)
(=(agent_dur dining_table stove_burner_1)21)
(=(agent_dur dining_table stove_burner_2)23)
(=(agent_dur dining_table stove_burner_3)20)
(=(agent_dur dining_table stove_burner_4)23)
(=(agent_dur dining_table countertop)23)
(=(agent_dur dining_table sink)22)
(=(agent_dur dining_table oven)16)
(=(agent_dur dining_table fridge)24)
(=(agent_dur dining_table dining_table)0)
(=(agent_dur dining_table dustbin_1)23)
(=(agent_dur dustbin_1 cabinet)48)
(=(agent_dur dustbin_1 rack)50)
(=(agent_dur dustbin_1 shelf)17)
(=(agent_dur dustbin_1 stove_burner_1)40)
(=(agent_dur dustbin_1 stove_burner_2)42)
(=(agent_dur dustbin_1 stove_burner_3)40)
(=(agent_dur dustbin_1 stove_burner_4)43)
(=(agent_dur dustbin_1 countertop)46)
(=(agent_dur dustbin_1 sink)36)
(=(agent_dur dustbin_1 oven)14)
(=(agent_dur dustbin_1 fridge)39)
(=(agent_dur dustbin_1 dining_table)23)
(=(agent_dur dustbin_1 dustbin_1)0)
(=(agent_dur cabinet laundrybag)66)
(=(agent_dur rack laundrybag)67)
(=(agent_dur shelf laundrybag)44)
(=(agent_dur stove_burner_1 laundrybag)52)
(=(agent_dur stove_burner_2 laundrybag)55)
(=(agent_dur stove_burner_3 laundrybag)54)
(=(agent_dur stove_burner_4 laundrybag)55)
(=(agent_dur countertop laundrybag)60)
(=(agent_dur sink laundrybag)48)
(=(agent_dur oven laundrybag)40)
(=(agent_dur fridge laundrybag)62)
(=(agent_dur dining_table laundrybag)41)
(=(agent_dur dustbin_1 laundrybag)32)
(=(agent_dur cabinet ironing_board)92)
(=(agent_dur cabinet closet)96)
(=(agent_dur cabinet working_table)80)
(=(agent_dur rack ironing_board)95)
(=(agent_dur rack closet)100)
(=(agent_dur rack working_table)83)
(=(agent_dur shelf ironing_board)58)
(=(agent_dur shelf closet)62)
(=(agent_dur shelf working_table)46)
(=(agent_dur stove_burner_1 ironing_board)87)
(=(agent_dur stove_burner_1 closet)92)
(=(agent_dur stove_burner_1 working_table)75)
(=(agent_dur stove_burner_2 ironing_board)90)
(=(agent_dur stove_burner_2 closet)94)
(=(agent_dur stove_burner_2 working_table)77)
(=(agent_dur stove_burner_3 ironing_board)88)
(=(agent_dur stove_burner_3 closet)92)
(=(agent_dur stove_burner_3 working_table)76)
(=(agent_dur stove_burner_4 ironing_board)90)
(=(agent_dur stove_burner_4 closet)95)
(=(agent_dur stove_burner_4 working_table)78)
(=(agent_dur countertop ironing_board)92)
(=(agent_dur countertop closet)97)
(=(agent_dur countertop working_table)81)
(=(agent_dur sink ironing_board)85)
(=(agent_dur sink closet)89)
(=(agent_dur sink working_table)73)
(=(agent_dur oven ironing_board)55)
(=(agent_dur oven closet)60)
(=(agent_dur oven working_table)44)
(=(agent_dur fridge ironing_board)81)
(=(agent_dur fridge closet)85)
(=(agent_dur fridge working_table)69)
(=(agent_dur dining_table ironing_board)69)
(=(agent_dur dining_table closet)74)
(=(agent_dur dining_table working_table)57)
(=(agent_dur dustbin_1 ironing_board)51)
(=(agent_dur dustbin_1 closet)55)
(=(agent_dur dustbin_1 working_table)39)
(=(agent_dur cabinet washingmachine)86)
(=(agent_dur rack washingmachine)89)
(=(agent_dur shelf washingmachine)52)
(=(agent_dur stove_burner_1 washingmachine)82)
(=(agent_dur stove_burner_2 washingmachine)85)
(=(agent_dur stove_burner_3 washingmachine)82)
(=(agent_dur stove_burner_4 washingmachine)85)
(=(agent_dur countertop washingmachine)87)
(=(agent_dur sink washingmachine)79)
(=(agent_dur oven washingmachine)50)
(=(agent_dur fridge washingmachine)75)
(=(agent_dur dining_table washingmachine)63)
(=(agent_dur dustbin_1 washingmachine)45)
(=(agent_dur laundrybag cabinet)66)
(=(agent_dur laundrybag rack)67)
(=(agent_dur laundrybag shelf)44)
(=(agent_dur laundrybag stove_burner_1)52)
(=(agent_dur laundrybag stove_burner_2)55)
(=(agent_dur laundrybag stove_burner_3)54)
(=(agent_dur laundrybag stove_burner_4)55)
(=(agent_dur laundrybag countertop)60)
(=(agent_dur laundrybag sink)48)
(=(agent_dur laundrybag oven)40)
(=(agent_dur laundrybag fridge)62)
(=(agent_dur laundrybag dining_table)41)
(=(agent_dur laundrybag dustbin_1)32)
(=(agent_dur laundrybag laundrybag)0)
(=(agent_dur laundrybag ironing_board)82)
(=(agent_dur laundrybag closet)87)
(=(agent_dur laundrybag working_table)70)
(=(agent_dur laundrybag washingmachine)77)
(=(agent_dur ironing_board cabinet)92)
(=(agent_dur ironing_board rack)95)
(=(agent_dur ironing_board shelf)58)
(=(agent_dur ironing_board stove_burner_1)87)
(=(agent_dur ironing_board stove_burner_2)90)
(=(agent_dur ironing_board stove_burner_3)88)
(=(agent_dur ironing_board stove_burner_4)90)
(=(agent_dur ironing_board countertop)92)
(=(agent_dur ironing_board sink)85)
(=(agent_dur ironing_board oven)55)
(=(agent_dur ironing_board fridge)81)
(=(agent_dur ironing_board dining_table)69)
(=(agent_dur ironing_board dustbin_1)51)
(=(agent_dur closet cabinet)96)
(=(agent_dur closet rack)100)
(=(agent_dur closet shelf)62)
(=(agent_dur closet stove_burner_1)92)
(=(agent_dur closet stove_burner_2)94)
(=(agent_dur closet stove_burner_3)92)
(=(agent_dur closet stove_burner_4)95)
(=(agent_dur closet countertop)97)
(=(agent_dur closet sink)89)
(=(agent_dur closet oven)60)
(=(agent_dur closet fridge)85)
(=(agent_dur closet dining_table)74)
(=(agent_dur closet dustbin_1)55)
(=(agent_dur working_table cabinet)80)
(=(agent_dur working_table rack)83)
(=(agent_dur working_table shelf)46)
(=(agent_dur working_table stove_burner_1)75)
(=(agent_dur working_table stove_burner_2)77)
(=(agent_dur working_table stove_burner_3)76)
(=(agent_dur working_table stove_burner_4)78)
(=(agent_dur working_table countertop)81)
(=(agent_dur working_table sink)73)
(=(agent_dur working_table oven)44)
(=(agent_dur working_table fridge)69)
(=(agent_dur working_table dining_table)57)
(=(agent_dur working_table dustbin_1)39)
(=(agent_dur ironing_board laundrybag)82)
(=(agent_dur closet laundrybag)87)
(=(agent_dur working_table laundrybag)70)
(=(agent_dur ironing_board ironing_board)0)
(=(agent_dur ironing_board closet)11)
(=(agent_dur ironing_board working_table)40)
(=(agent_dur closet ironing_board)11)
(=(agent_dur closet closet)0)
(=(agent_dur closet working_table)37)
(=(agent_dur working_table ironing_board)40)
(=(agent_dur working_table closet)37)
(=(agent_dur working_table working_table)0)
(=(agent_dur ironing_board washingmachine)40)
(=(agent_dur closet washingmachine)50)
(=(agent_dur working_table washingmachine)57)
(=(agent_dur washingmachine cabinet)86)
(=(agent_dur washingmachine rack)89)
(=(agent_dur washingmachine shelf)52)
(=(agent_dur washingmachine stove_burner_1)82)
(=(agent_dur washingmachine stove_burner_2)85)
(=(agent_dur washingmachine stove_burner_3)82)
(=(agent_dur washingmachine stove_burner_4)85)
(=(agent_dur washingmachine countertop)87)
(=(agent_dur washingmachine sink)79)
(=(agent_dur washingmachine oven)50)
(=(agent_dur washingmachine fridge)75)
(=(agent_dur washingmachine dining_table)63)
(=(agent_dur washingmachine dustbin_1)45)
(=(agent_dur washingmachine laundrybag)77)
(=(agent_dur washingmachine ironing_board)40)
(=(agent_dur washingmachine closet)50)
(=(agent_dur washingmachine working_table)57)
(=(agent_dur washingmachine washingmachine)0)



   

    ( = (total-cost) 0) 

;; Food remianing in fridge
    
; (cooked cooked_Cereal)
; (stuff_at cooked_Cereal fridge kitchen)
    
  (baked cake)
  (stuff_at cake fridge kitchen)
  (is_vc vacuum_Cleaner)
     
;  (free)
)

(:goal
    (and

    (laundrydone)
    )
)


(:metric minimize (total-cost))


)


;; TO DO

; Optimization

;; High-priority
; Vacuum cleaning should not overlap with other actions. \\Done
; sometimes human/agent is holding way too many things in hand and doing work. \\Done
; vacuum cleaner is switched on beforehand \\ Done
; Gotta scale the duration between 0 to 100. \\ Done
; Why they are holding hose? \\Done

;; Low-priority
; tray for serving
; Addmop to clean the room.


;; Cost will be divided on the basis of
; task effort
; task type (repetetive or not)
; Who is nearer
; Object type
; Speed of Human/Agent



;; Changes made

; (agent_hands_occupied),(human_hands_occupied), (heavy_obj_in_human_hand), (heavy_obj_in_agent_hand) predicates added. \\ Done in order to avoid carrying something while doing important work like cooking, cleaning or any major work.

; (fully_occupied ?r) \\ Under process \\ Deleted; not useful.

; Change in human and robot moving speed. Human is 1.3x faster.

; Added tray.

; obj_at -> B_obj_at

; receptacle is not under obj type. \\ it was putting plate into metal_pot.










;;For goal_2


;; Changes made

; is_vc \\ to fix hose problem; Working well

; (not_burner ?r)  \\avoiding placing objects on burner; Working well

; (human_hands_occupied_wo)  \\ For stronger preconditions; still experimenting if this is good or not.
; (agent_hands_occupied_wo)
; (human_hands_occupied_wr)
; (agent_hands_occupied_wr)



; \\ In order to negate the occupied_hand predicate, agent is picking and placing random objects. Gota fix that.
; (agent_pickup roasted_sandwich stove_burner_3 kitchen)
; (agent_moves_br stove_burner_3 dining_table kitchen kitchen)
; (agent_pickup cellphone dining_table kitchen)
; (agent_putdowns cellphone dining_table kitchen)
; (agent_picksup_object vacuum_cleaner kitchen)


; Burner 1,2,3,4 changed to Burner.
; Cost for handling big object (VC), switching, holding hose  is same now.
; pickup and putdown has same cost now \\ stuff_at