master_tasks = [
    "prepare breakfast (omelette)",
    "prepare breakfast (boiled_eggs)",
    "prepare breakfast (scrambled_eggs)",
    "prepare breakfast (salad)",
    "prepare breakfast (mashed_potatoes)",
    "prepare breakfast (mix_veggy)",
    "prepare breakfast (fruit_salad)",
    "prepare breakfast (toast)",
    "prepare breakfast (cereal)",
    "prepare breakfast (cake)",
    "prepare breakfast (pizza)",
    "prepare breakfast (noodles)",
    "prepare breakfast (pasta)",
    "prepare breakfast (coke)",
    "prepare breakfast (ice_tea)",
    "prepare breakfast (sugary_fruit_juice)",
    "prepare breakfast (samosa)",
    "prepare breakfast (fried_rice)",
    "prepare breakfast (fried_chicken)",
    "prepare breakfast (chips)",
    "prepare lunch (rice)",
    "prepare lunch (yogurt)",
    "prepare lunch (soup)",
    "prepare lunch (mix_veggy)",
    "prepare lunch (lentil)",
    "prepare lunch (cake)",
    "prepare lunch (pizza)",
    "prepare lunch (noodles)",
    "prepare lunch (pasta)",
    "prepare lunch (coke)",
    "prepare lunch (ice_tea)",
    "prepare lunch (sugary_fruit_juice)",
    "prepare lunch (samosa)",
    "prepare lunch (fried_rice)",
    "prepare lunch (fried_chicken)",
    "prepare lunch (chips)",
    "prepare dinner (rice)",
    "prepare dinner (veggies)",
    "prepare dinner (yogurt)",
    "prepare dinner (soup)",
    "prepare dinner (mix_veggy)",
    "prepare dinner (lentil)",
    "prepare dinner (cake)",
    "prepare dinner (pizza)",
    "prepare dinner (noodles)",
    "prepare dinner (pasta)",
    "prepare dinner (coke)",
    "prepare dinner (ice_tea)",
    "prepare dinner (sugary_fruit_juice)",
    "prepare dinner (samosa)",
    "prepare dinner (fried_rice)",
    "prepare dinner (fried_chicken)",
    "prepare dinner (chips)",
    "serve the food on (food options) (receptacle options)",
    "serve a drink (water)",
    "serve a drink (coke)",
    "serve a drink (ice_tea)",
    "serve a drink (sugary_fruit_juice)",
    "serve a drink (milk)",
    "serve a drink (coffee)",
    "serve a drink (tea)",
    "prepare medicines",
    "wash the dishes",
    "do the laundry",
    "prepare clothes (office)",
    "prepare clothes (casual)",
    "prepare clothes (gym)",
    "charge electronic device (cellphone)",
    "charge electronic device (laptop)",
    "prepare the office bag",
    "clean the room (kitchen)",
    "clean the room (bathroom)",
    "clean the room (bedroom)",
    "clean the room (living_room)",
    "set up the office table",
    "throw away leftover food",
    "put remaining food in the fridge",
    "decorate the place",
    "dust electronic devices",
    "extinguish the fire",
]
