task_user_1 = [
    "clean the room (livingroom) (using vacuum cleaner)",
    "prepare breakfast (boiled eggs)",
    "set up the office table",
    "serve the food (food=boiled eggs) (location=office table)",
    "serve the drink (drink=coffee) (location=office table)",
    "prepare lunch (sandwich)",
    "serve lunch (sandwich) (location=dining table)",
    "wash the dishes",
    "put remaining food in the fridge",
    "prepare dinner (rice)",
    "serve dinner (rice) (location=dining table)",
    "prepare medicines",
    "wash the dishes",
    "put remaining food in the fridge",
    "serve dinner (mixed vegetables) (location=dining table)",
    "prepare medicines",
    "charge the electronic devices",
    "do the laundry",
    "prepare clothes (casual)",
    "prepare clothes (gym)",
    "prepare clothes (office)",
    "charge the electronic devices (cellphone)",
    "charge the electronic devices (laptop)",
    "prepare office bag",
    "clean the room (kitchen) (using vacuum cleaner)",
    "clean the room (bathroom) (using mop)",
    "prepare lunch (soup)",
    "serve a drink (milk) (location=dining table)",
    "serve a drink (tea) (location=dining table)",
]
